src/card.js
src/card.styles.js

[TASK] Add loading indicator

---

src/card.js

[BUGFIX] Fix weather offset when forecast does not start today

---

README.md
src/card.js

[TASK] Add option to start with different day than today

---

hacs.json
src/card.js

[BUGFIX] Change weather forecast to use websockets

---

README.md
src/card.js
src/card.styles.js

[TASK] Add option to show event location in overview

---

src/card.js

[BUGFIX] Fix infinite loading after a while when weather is enabled

---

README.md
src/card.js

[FEATURE] Add option to hide past events

---

src/card.js

[BUGFIX] Fix timezone problem when fetching calendar events

---

src/card.js

[BUGFIX] Make sure the starting date is correct when updating events

---

src/card.js

This adds `data-date`, `data-weekday`, `data-month`, `data-year` and `data-week` attributes to the day container tag. It can be used for custom styling.
Resolves: #116

[FEATURE] Add data attributes for date parts

---

README.md
src/card.js

This adds an option `filter` to filter out any event that matches a regular expression
Resolves: #67

[FEATURE] Add event filter

---

src/card.js

This prevents events with the same start time from jumping around when calendars are (re)loaded
Resolves: #74

[FEATURE] Make sure events with the same starting date are sorted by calendar

---

README.md

[DOCS] Fix typo

---

src/card.styles.js

[BUGFIX] Fix legend styling bug

---

README.md
src/card.js

[FEATURE] Add event filter per calendar

---

README.md
src/card.js
src/card.styles.js

[FEATURE] Add card actions

---

README.md
src/card.js

[FEATURE] Add option to hide calendar in legend

---

README.md
package-lock.json
package.json

[TASK] Increase version to 1.8.0

---

src/card.js

This can be used for custom styling using card_mod.
Resolves: #141

[FEATURE] Add additional data attributes to event div

---

README.md

[DOCS] Add documentation about data attributes

---

README.md
package-lock.json
package.json

[TASK] Increase version to 1.9.0

---

README.md
src/card.js
src/card.styles.js
src/editor.js

[FEATURE] Add option for calendar icons

---

README.md
src/card.js
src/editor.js

[FEATURE] Add options to filter event text

---

README.md
package-lock.json
package.json

[TASK] Increase version to 1.10.0

---

src/editor.js
src/editor.styles.js

[FEATURE] Add entity picker and icon picker to visual editor

---

README.md
package-lock.json
package.json

[TASK] Increase version to 1.10.1

---

README.md
src/card.js
src/card.styles.js
src/editor.js

[FEATURE] Add options to override the number of columns

---

README.md

[DOCS] Update manual installation documentation

---

README.md
src/card.js
src/editor.js

Also add option to override event title field name per calendar
Resolves: #202

[FEATURE] Add option to show/hide event title and description

---

README.md
src/card.js
src/card.styles.js
src/editor.js

[FEATURE] Add options to limit the number of events shown

---

src/card.js

[BUGFIX] Only rerender everything when something changes

---

README.md
package-lock.json
package.json

[TASK] Increase version to 1.11.0

---

src/editor.js

[BUGFIX] Fix adding and removing calendars with visual editor

---

README.md
package-lock.json
package.json

[TASK] Increase version to 1.11.1

---

README.md
src/card.js

[FEATURE] Add options to search and replace text from event titles

---

README.md
package-lock.json
package.json

[TASK] Increase version to 1.12.0

---

src/card.js

[BUGFIX] Fix calendar event sorting
